sudo: false
dist: xenial
language: python
addons:
  apt:
    update: true
virtualenv:
  system_site_packages: true
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
install:
  - pip install .
  - pip install -r requirements.txt
script: sh run_travis.sh
after_success:
  #- export CODECOV_TOKEN=":uuid-repo-token"
  - bash < (curl -s https://codecov.io/bash)
notifications:
  - email: false
