sudo: false
dist: trusty
language: python
addons:
  apt:
    update: true
virtualenv:
  system_site_packages: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
install:
 - sudo apt-get update
 - pip install --upgrade pip setuptools
 - pip install --upgrade pip virtualenv
 - pip install coverage -U
 - pip install pyflakes -U
 - pip install nose -U
 - pip install tox-travis
 #- pip install -U --process-dependency-links -e .[develop]
 - pip install --upgrade pytest
script:
  - pip install .
  - pip install -r requirements.txt
  - sh run_travis.sh
after_success:
  #- export CODECOV_TOKEN=":uuid-repo-token"
  - bash < (curl -s https://codecov.io/bash)
notifications:
  - email: false
