sudo: false
dist: trusty
language: python
addons:
  apt:
    update: true
virtualenv:
  system_site_packages: true
python:
  - "2.7"
  - "3.4"
install:
 - sudo apt-get update
 - pip install --upgrade pip setuptools
 - pip install --upgrade pip virtualenv
 - pip install coverage -U
 - pip install pyflakes -U
 - pip install nose -U
 - pip install tox-travis
 - pip install codecov -U
 - pip install --upgrade pytest
script:
  - pip install .
  - pip install -r requirements.txt
  - sh run_travis.sh
after_success:
  - codecov
notifications:
  - email: false
